### ISSUE TITLE
Add walpapers

### ISSUE THREAD

**Issue by Raven-002** [Raven-002/Raven-DE#19]
- [X] Use hyprland anime girl wallpaper as default
- [X] Add arch linux logo wallpapers
- [ ] Add cat fishing wallpaper
- [X] Set cats fishing wallpaper as default via hyprpaper
- [ ] Verify the paths used in hyprpaper
- [ ] Verify the location for the images in the package

**Comment by ayaOwO** [comment]
Note, paths must start with ~ or be absolute

**Comment by ayaOwO** [comment]
Yay this is the best!
